### ISSUE TITLE
Method not found after Kdyby/Doctrine update (namespace issue)

### ISSUE THREAD

**Issue by foowie** [Kdyby/DoctrineMoney#4]
```
[Doctrine\ORM\Mapping\MappingException]                                                                                             
  Entity Listener "Kdyby\DoctrineMoney\Mapping\MoneyObjectHydrationListener" declared on "MyClassWithMoneyField has no method "Doctrine\ORM\Event::postLoadRelations".
```

Since this commit https://github.com/Kdyby/Doctrine/commit/5c416e363dad8d6939b96ef72eca74533dd5c182, events are namespaced. This is OK, but Kdyby\Doctrine\Events::postLoadRelations constant is used also for local method name (3rd parameter)  in https://github.com/Kdyby/DoctrineMoney/blob/master/src/Kdyby/DoctrineMoney/Mapping/MoneyObjectHydrationListener.php#L201 .

**Comment by foowie** [comment]
I found pull request #3, but still an issue since plugin is not working because of this.

**Comment by fprochazka** [comment]
This repo is currently kind of broken. That's why I've tagged Money and DoctrineMoney so you can lock yourself on the older revisions till it's fixed.
